### ISSUE TITLE
Requirements and Design Outline

### ISSUE THREAD

**Issue by XoloKDandashe** [XoloKDandashe/Alpha-Tech#6]
Detailed description of the requirements needed to achieve product functionality as well as design layout that will be used to make the application appealing.

**Comment by ThaboNtsoane** [comment]
I have done the Requirements

**Comment by ThaboNtsoane** [comment]
The Design Outline is still required

**Comment by XoloKDandashe** [comment]
We will brainstorm ideas on layouts and data presentation ideas we can do.

**Comment by ThaboNtsoane** [comment]
Done with features and friendly user icons for the design outline

**Comment by musamathe354** [comment]
I am done with the following sections- Targeted audience for the app, user experience and how the app will be used so we need to combine our parts
