### ISSUE TITLE
Demo Prototype Design

### ISSUE THREAD

**Issue by XoloKDandashe** [XoloKDandashe/Alpha-Tech#9]
Design layout for the application prototype.

**Comment by XoloKDandashe** [comment]
I will be joining the Prototype Design.

**Comment by musamathe354** [comment]
I was checking at https://www.000webhost.com for hosting free in terms of the database but I heard you say you wanted to use a list so Ill try test my method first then I guess we will check which one will be suitable for demo.

**Comment by XoloKDandashe** [comment]
Designs have been completed for the prototype.
